@WebApiExample_HostAddress = http://localhost:5045

GET {{WebApiExample_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApiExample_HostAddress}}/weatherforecast?country=France
Accept: application/json

###
